/* Automatically generated by './build/bin/build-entry.js' */

import Svgedit from '../packages/svgedit/index.js';
import Svgitem from '../packages/svgitem/index.js';
import Svgleft from '../packages/svgleft/index.js';
import Svgpreview from '../packages/svgpreview/index.js';
import Svgright from '../packages/svgright/index.js';
import Virtuallist from '../packages/virtuallist/index.js';


const components = [
  Svgedit,
  Svgitem,
  Svgleft,
  Svgpreview,
  Svgright,
  Virtuallist
];

const install = function(Vue) {
  components.forEach(component => {
    Vue.component('yx' + component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.7',
  install,
  Svgedit,
  Svgitem,
  Svgleft,
  Svgpreview,
  Svgright,
  Virtuallist
};
