/* Automatically generated by './build/bin/build-entry.js' */

import SvgEdit from '../packages/svgedit/index.js';
import SvgItem from '../packages/svgcomponents/index.js';
import LeftToolBar from '../packages/svgleft/index.js';
import SvgPreview from '../packages/svgpreview/index.js';
import RightToolBar from '../packages/svgright/index.js';

const components = [
  SvgEdit,
  SvgItem,
  LeftToolBar,
  SvgPreview,
  RightToolBar
];

const install = function(Vue) {
  components.forEach(component => {
    Vue.component('yx' + component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.6',
  install,
  SvgEdit,
  SvgItem,
  LeftToolBar,
  SvgPreview,
  RightToolBar
};
