/* Automatically generated by './build/bin/build-entry.js' */

import SvgEdit from '../packages/svgedit/index.js';
import SvgItem from '../packages/svgcomponents/index.js';
import LeftToolBar from '../packages/svgleft/index.js';
import SvgPreview from '../packages/svgpreview/index.js';
import RightToolBar from '../packages/svgright/index.js';

const components = [
  SvgEdit,
  SvgItem,
  LeftToolBar,
  SvgPreview,
  RightToolBar
];

import Fragment from 'vue-fragment';
import baseComponents from 'main/assets/json/InterfaceReturn.json';

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component('yx' + component.name, component);
  });
  Vue.use(Fragment.Plugin);
  baseComponents.forEach((e) => {
    let com1 = Vue.extend({
      props: e.props,
      template: `<fragment>${e.template}</fragment>`
    });
    Vue.component(e.type, com1);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.1',
  install,
  SvgEdit,
  SvgItem,
  LeftToolBar,
  SvgPreview,
  RightToolBar
};
